import { FieldDefinition } from "../types";

export const UMPSA_PRESET_FIELDS: FieldDefinition[] = [
  {
    name: "Date",
    pageIndex: 2,
    rect: {
      x: 115.5,
      y: 100,
      width: 92,
      height: 15,
    },
    role: "date",
    id: "p3-date",
  },
  {
    name: "Day",
    pageIndex: 2,
    rect: {
      x: 248.5,
      y: 100,
      width: 107,
      height: 15,
    },
    role: "day",
    id: "p3-day",
  },
  {
    name: "Week Number",
    pageIndex: 2,
    rect: {
      x: 430.5,
      y: 100,
      width: 16,
      height: 15,
    },
    role: "week",
    id: "p3-week",
  },
  {
    name: "Activity",
    pageIndex: 2,
    rect: {
      x: 71.5,
      y: 184.2,
      width: 479,
      height: 500,
    },
    role: "text",
    id: "p3-activity",
  },
  {
    name: "Week Number",
    pageIndex: 8,
    rect: {
      x: 284.5,
      y: 87.4,
      width: 22,
      height: 12,
    },
    role: "week",
    id: "p9-week-top",
  },
  {
    name: "Date",
    pageIndex: 8,
    rect: {
      x: 332.5,
      y: 82,
      width: 106,
      height: 15,
    },
    role: "date",
    id: "p9-date-top",
  },
  {
    name: "Work Details",
    pageIndex: 8,
    rect: {
      x: 66.5,
      y: 146,
      width: 85,
      height: 283,
    },
    role: "text",
    id: "p9-work-details",
  },
  {
    name: "What did I learn",
    pageIndex: 8,
    rect: {
      x: 161.5,
      y: 146,
      width: 132,
      height: 283,
    },
    role: "text",
    id: "p9-learning",
  },
  {
    name: "How does this relate",
    pageIndex: 8,
    rect: {
      x: 302.5,
      y: 146,
      width: 254,
      height: 283,
    },
    role: "text",
    id: "p9-relation",
  },
  {
    name: "Date",
    pageIndex: 8,
    rect: {
      x: 95.5,
      y: 610,
      width: 85,
      height: 14,
    },
    role: "date",
    id: "p9-date-bottom",
  },
  {
    name: "Week Number",
    pageIndex: 8,
    rect: {
      x: 140,
      y: 750.1,
      width: 16,
      height: 12,
    },
    role: "week",
    id: "p9-week-bottom",
  },
];
